image: cappero_laser_odom_diag_2020-05-06-16-26-03.png
resolution: 0.02   # Match the resolution from the .world file
origin: [-19.6, -5.0, 0.015]  # Origin based on floorplan size/pose
occupied_thresh: 0.65
free_thresh: 0.196
negate: 0
